// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ShippingClientPort is an autogenerated mock type for the ShippingClientPort type
type ShippingClientPort struct {
	mock.Mock
}

// Ship provides a mock function with given fields: ctx, orderId, address
func (_m *ShippingClientPort) Ship(ctx context.Context, orderId int64, address string) error {
	ret := _m.Called(ctx, orderId, address)

	if len(ret) == 0 {
		panic("no return value specified for Ship")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, orderId, address)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewShippingClientPort creates a new instance of ShippingClientPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShippingClientPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShippingClientPort {
	mock := &ShippingClientPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
